### ISSUE TITLE
Person / profile

### ISSUE THREAD

**Issue by jcavell** [ministryofjustice/hmpps-book-secure-move-api#385]
**Currently**
- A person (people table) has very little in it (just nomis_prison_number and attached image)
- A person has the concept of a ‘latest profile'
- A move relates to a person not a profile
- A person has a list of profiles (in theory; in practice, it's a 1-2-1 relationship)
- Each profile has name, dob, gender, ethnicity, profile_identifiers, and has latest_nomis_booking_id

**Issues**

- There is no explicit link between move and profile, only between move and person, mediated by latest_profile. This means that if a profile is updated, it will appear to be updated for all moves (future and past) because we get a person’s profile by using latest_profile
- Additionally, currently creating a new move will update the existing profile rather than create a new one
- We have duplication (in profile) of name, dob, gender, ethnicity and profile_identifiers
- 'GETting' people via a filter results in sync of latest_profile from NOMIS if prison_number is provided. This should be more explicit and probably sync person rather than profile (see below)

**Nirvana - the API**

- A move contains a profile
- A profile has a link to person
- A person contains a list of profiles and list of moves

**Options**
- Change code so that a profile belongs to a move. Change API to that proposed above
- Get rid of latest_profile and rename profile.latest_nomis_booking_id to profile.nomis_booking_id
- Change person to also have name, dob, gender, ethnicity. These fields on profile become a snapshot in time whereas on person they are 'current' or even sometimes 'synced' from an original data source such as NOMIS (TBC because this may not be desired)
- Move profile_identifiers from profile to person

**Comment by teneightfive** [comment]
Thanks for getting this down @jcavell and starting us off. 

To give a bit a history and context about the split...

We started off with two entities `Person` and `Profile` with the plan for `Person` to contain "fixed" data like `first_names`, `last_name`, `date_of_birth`, `gender`, `ethnicity` and `Profile` to contain data that we know would likely change with each move like the risk assessment or health assessment.

However, we discovered that the actual reality of this service is that a large number of what we thought was "fixed" data wasn't actually fixed. For example, somebody could change their name or gender between being arrested. The decision was then taken to move everything to `Profile` for simplicity at the time, but that has caused us the problems you have described above further down the line.

## Moving forward

Here are some things I think we need to do to solve this moving forward that will also support backwards compatibility. 

### Step 1

#### Create relationship between `moves` and `profiles`

The biggest problem right now is that any past moves will always display the latest information we have for a person, which is a big problem for auditing. 

I'm not sure how possible it is to associate a profile that was created at the same time as the move with a move?

If that's too tricky we might have to just associate the latest current profile when doing that migration.

I'd then expect the move to return a response like this:

```json
{
  "data": {
    "id": "007f6aa0-7d82-4bf1-9191-2e27235d0f76",
    "type": "moves",
    "attributes": {
      "reference": "KVU1456M",
      ...
    },
    "relationships": {
      "profile": {
        "data": {
          "id": "2c952ca0-f750-4ac3-ac76-fb631445f974",
          "type": "profiles"
        }
      },
      "person": {
        "data": {
          "id": "5a3631de-3a60-4dc3-841c-f3095b33d0f9",
          "type": "people"
        }
      },
      ...
    }
  },
  "included": [
    {
      "id": "5a3631de-3a60-4dc3-841c-f3095b33d0f9",
      "type": "people",
      "attributes": {
        "first_names": "Nicki",
        "last_name": "Parker",
        "date_of_birth": "1994-11-12",
        "assessment_answers": [
          {
            "title": "Escape",
            "comments": "Large poster in cell",
            "created_at": "2019-08-26",
            "expires_at": null,
            "assessment_question_id": "76e00bf9-55f6-4ea5-b018-2c47d060caf5",
            "category": "risk",
            "key": "escape"
          },
          {
            "title": "Any other risks",
            "comments": "",
            "created_at": "2019-08-26",
            "expires_at": null,
            "assessment_question_id": "227c6348-4f15-4bf1-a2ed-4b89819254d1",
            "category": "risk",
            "key": "other_risks"
          },
          {
            "title": "Must be held separately",
            "comments": "Infectious skin disorder",
            "created_at": "2019-08-26",
            "expires_at": null,
            "assessment_question_id": "bca4f1c1-cea1-417d-b1b4-bdf22951ce5b",
            "category": "risk",
            "key": "hold_separately"
          }
        ],
        "identifiers": [
          {
            "identifier_type": "police_national_computer",
            "value": "585323"
          },
          {
            "identifier_type": "prison_number",
            "value": "512913"
          }
        ],
        "gender_additional_information": null
      },
      "relationships": {
        "ethnicity": {
          "data": {
            "id": "321ac790-ce9b-4fbc-9f2d-f7a0f647a77a",
            "type": "ethnicities"
          }
        },
        "gender": {
          "data": {
            "id": "88ea3094-11ab-47d5-8c13-f62546fafc5c",
            "type": "genders"
          }
        }
      }
    },
    {
      "id": "2c952ca0-f750-4ac3-ac76-fb631445f974",
      "type": "profiles",
      "attributes": {
        "first_names": "Nicki",
        "last_name": "Parker",
        "date_of_birth": "1994-11-12",
        "assessment_answers": [
          {
            "title": "Escape",
            "comments": "Large poster in cell",
            "created_at": "2019-08-26",
            "expires_at": null,
            "assessment_question_id": "76e00bf9-55f6-4ea5-b018-2c47d060caf5",
            "category": "risk",
            "key": "escape"
          },
          {
            "title": "Any other risks",
            "comments": "",
            "created_at": "2019-08-26",
            "expires_at": null,
            "assessment_question_id": "227c6348-4f15-4bf1-a2ed-4b89819254d1",
            "category": "risk",
            "key": "other_risks"
          },
          {
            "title": "Must be held separately",
            "comments": "Infectious skin disorder",
            "created_at": "2019-08-26",
            "expires_at": null,
            "assessment_question_id": "bca4f1c1-cea1-417d-b1b4-bdf22951ce5b",
            "category": "risk",
            "key": "hold_separately"
          }
        ],
        "identifiers": [
          {
            "identifier_type": "police_national_computer",
            "value": "585323"
          },
          {
            "identifier_type": "prison_number",
            "value": "512913"
          }
        ],
        "gender_additional_information": null
      },
      "relationships": {
        "ethnicity": {
          "data": {
            "id": "321ac790-ce9b-4fbc-9f2d-f7a0f647a77a",
            "type": "ethnicities"
          }
        },
        "gender": {
          "data": {
            "id": "88ea3094-11ab-47d5-8c13-f62546fafc5c",
            "type": "genders"
          }
        }
      }
    },
    ...
  ]
}
```

NB. I've used ellipsis to denote existing attributes and relationships. 

For now this would return the same information under the `person` and `profile` relationships to not break existing implementations.

#### Update how `POST /moves` works

To support the new relationship and existing implementations we would need to still allow a move to be created with a `person` relationship, but when that is sent, the API should get the latest profile (that would have just been created) and associate that `profile` with a move.

This will be a temporary measure until we fully fix the relationship around people and profiles. But the key is to not make too many breaking changes to the API.

#### Update frontend to use `move.profile` instead of `move.person`

The frontend uses the information that is returned on the `person` relationship, which as mentioned above will always return the latest rather than the details that were created at the same point the move was created.

We will need to update how the frontend gets and displays that data for old moves.

#### Add `PATCH /profiles` endpoint

Once a move returns which profile is associated with it, we will need to support editing of just that `profile` so that old moves aren't effected by these updates.

**Question**: What should we do with the `POST /people` response? Should it return the profile that was created as a one-to-one relationship? The frontend needs to make a `PATCH` call during the create process to update the profile with the assessment as the user goes along, at the moment we call `PATCH /people` but that will currently create a new profile - is that correct?

So after a `POST /people` we need a way to be able to update just that `profile`, before or after associating it with a `move`.

### Step 2

#### Show relationship between `people` and `profiles`

A `person` should have a 1-to-many relationship with `profiles`. That should be returned by the API on a person too.

We may also want to decide to somehow indicate the latest `profile` in the response for things like the person lookup. We could potentially use a different response on `GET /people` to `GET /people/:PersonId` and not return all profiles. I think JSON:API gives the ability to define what is included or not to some extent (need to check the docs though).

#### Look at deprecating existing relationships

Once we have a solid implementation we could look at removing the `move`/`person` relationship and relying on the relationship between `profile` and `person` to bring back that information if necessary.

**Comment by willfish** [comment]
Closing this as solved.
